#+TITLE: Edwin

Edwin is a dynamic window manager for Emacs. It automatically arranges your
Emacs panes (called "windows" in Emacs parlance) into predefined layouts,
[[https://dwm.suckless.org/][dwm]]-style.

* Status

Edwin is new and experimental. While it works very well on the subset
of Emacs that I use, you will definitely encounter bugs if you venture
outside of that. Patches welcome!

* Installation

Copy or clone Edwin somewhere on your system:

#+BEGIN_SRC sh
  git clone https://github.com/ajgrf/edwin ~/.emacs.d/edwin
#+END_SRC

Then add its location to =load-path=:

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path
               (expand-file-name "~/.emacs.d/edwin"))
#+END_SRC

* Concepts

Edwin divides the frame into 2 areas, the master area and the stack.
The master area contains the largest window(s), and other windows are
placed in the stack.

#+BEGIN_EXAMPLE
+-----------+---------+
|           |    1    |
|           +---------+
|  master   |    2    |
|           +---------+
|           |    3    |
+-----------+---------+
#+END_EXAMPLE

If the frame is too narrow for 2 columns, Edwin will instead put the
master area on top:

#+BEGIN_EXAMPLE
+------------+
|            |
|  master    |
|            |
+------------+
|     1      |
+------------+
|     2      |
+------------+
#+END_EXAMPLE

* Key Bindings

|----------------+--------------------------------------|
| Binding        | Action                               |
|----------------+--------------------------------------|
| =M-r=          | Arrange windows                      |
| =M-j=          | Move to next window                  |
| =M-k=          | Move to previous window              |
| =M-S-j=        | Swap places with the next window     |
| =M-S-k=        | Swap places with the previous window |
| =M-h=          | Decrease the size of the master area |
| =M-l=          | Increase the size of the master area |
| =M-d=          | Decrease number of windows in master |
| =M-i=          | Increase number of windows in master |
| =M-S-c=        | Delete window                        |
| =M-<return>=   | Cycle window to/from master area     |
| =M-S-<return>= | Clone current window                 |
|----------------+--------------------------------------|

* Scope

Edwin does not provide workspaces or window rules, instead delegating
such functionality to other plugins and Emacs facilities (like
[[https://github.com/wasamasa/eyebrowse][eyebrowse]]).

I recommend setting ~display-buffer~ to open a new window by default,
then defining any exceptions in ~display-buffer-alist~.

#+BEGIN_SRC emacs-lisp
  (setq display-buffer-base-action '(display-buffer-below-selected))
#+END_SRC
